[[language]]
name = "python"
file-types = ["py", "pyi"]
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
formatter = { command = "black", args = ["-", "-q"] }
